export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';
export const RECIEVER_LOADED = 'RECIEVER_LOADED';
export const DONOR_LOADED = 'DONOR_LOADED';
export const LOADING_ERROR = 'LOADING_ERROR';
export const RECIEVER_LOADING_ERROR = 'RECIEVER_LOADING_ERROR';
export const DONOR_LOADING_ERROR = 'DONOR_LOADING_ERROR';
export const SEARCHING_SUCCESS = 'SEARCHING_SUCCESS';
export const SEARCHING_FAIL = 'SEARCHING_FAIL';




